baseURL = 'https://dives.fyi'
languageCode = 'en-us'
title = 'Dives Research'
theme = 'dives'

[languages]
    [languages.en]
        contentDir = 'content/english'
        languageName = 'EN'
        weight = 10
    [languages.tr]
        contentDir = 'content/turkce'
        languageName = 'TR'
        weight = 20
